### PR TITLE
Login page

### PR DESCRIPTION
**Pull request by parvez-rashid**
View the screenshot below, preview link has some problem.

image

### CODE REVIEW

**Review by j24m — APPROVED** [review]
UI looks simple and nice, code seems fine to me, class names are understandable, PR is small.
Good work :)

**Review by manish-GH — APPROVED** [review]
For some reason, your netlify deploy seems to have failed. 
This is a small PR, the code has no issues, it can be merged

**Comment by parvez-rashid** [comment]
> For some reason, your netlify deploy seems to have failed. This is a small PR, the code has no issues, it can be merged

Yes that's because I changed the folder name in the branch. I'll try to fix it.

**Comment by parvez-rashid** [comment]
> UI looks simple and nice, code seems fine to me, class names are understandable, PR is small. Good work :)

Thank you for your time and good words!

**Pull request merged**
